import Head from 'next/head'
import { css } from '../../styled-system/css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={css({ fontSize: '2xl', fontWeight: 'bold', color: 'red' })}>Hello 🐼!</div>
      </main>
    </>
  )
}
