@startuml
skinparam PackageStyle rectangle

package 自分史集約 {
    object カード {
        カードID
        タイトル
        内容
        削除日
        分析結果
    }
}

note top of カード
    * タイトル必須、内容任意
    * 削除日は最初はNULLで、削除されたときに設定される
    * 分析結果は最初はNULLで、分析されたときに設定される
end note

package ユーザ集約 {
    object ユーザ {
        ユーザID
        ユーザ名
        メールアドレス
    }
}

note top of ユーザ
    * ユーザ名はデフォルトでユーザIDと同じ値が設定され、後で変更可能
    * パスワードレスの認証機構を使う
end note

カード "0..n" -right-> "1" ユーザ

@enduml