import { Header } from '@/components/common'
import Head from 'next/head'
import { center, hstack, vstack } from '../../../styled-system/patterns'
import { css } from '../../../styled-system/css'
import { Analyzing } from '@/components/views'
import { useState } from 'react'
import { FadeInWrapper } from '@/components/common/framer-motion/FadeInWrapper'
import { ViewButtons } from '@/components/views'

export default function Analysis() {
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const handleAnalyze = () => {
    setIsAnalyzing(true)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />

        <ViewButtons />
        <FadeInWrapper>
          <div
            className={css({
              w: '720px',
              h: '480px',
              mx: 'auto',
              px: '40px',
              py: '24px',
              bg: 'white',
              rounded: '14px',
              shadow: 'xl',
            })}
          >
            <div className={hstack({ justify: 'space-between' })}>
              <div
                className={css({
                  minW: '360px',
                  p: '24px',
                  shadow: 'xl',
                  rounded: '3xl',
                  bg: 'slate.100',
                })}
              >
                <h2 className={css({ fontSize: '2xl', fontWeight: 'bold' })}>開発インターン</h2>
                <p className={css({ fontSize: 'md', mt: '8px', color: 'dimGray' })}>
                  実務を通して、様々な学びを得た話
                </p>
              </div>
              <div className={vstack({ alignItems: 'start' })}>
                <p className={css({ fontSize: '2xl', fontWeight: 'bold' })}>について</p>
                <button
                  className={css({
                    bg: 'dimBlue',
                    fontWeight: 'medium',
                    fontSize: '20px',
                    color: 'white',
                    p: '12px',
                    rounded: '12px',
                    cursor: 'pointer',
                  })}
                  onClick={handleAnalyze}
                >
                  AIで自己の特性を知る
                </button>
              </div>
            </div>
            <div
              className={css({ w: 'full', h: '4px', bg: 'slate.200', mt: '24px', rounded: 'full' })}
            />
            <div className={center({ w: 'full', h: '280px' })}>
              {isAnalyzing ? (
                <Analyzing />
              ) : (
                <p className={css({ fontSize: 'lg', color: 'dimGray' })}>
                  AIで自分の特性を分析してみよう!
                </p>
              )}
            </div>
          </div>

          {/* <div
            className={hstack({
              w: '1200px',
              h: '320px',
              mx: 'auto',
              mt: '24px',
              gap: '32px',
              overflowX: 'auto',
            })}
          >
            <Card />
          </div> */}
        </FadeInWrapper>
      </main>
    </>
  )
}
